# Generated by Django 3.2.6 on 2021-12-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slidesdata',
            table='slides_data',
        ),
    ]
