# Generated by Django 3.2.6 on 2021-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_slidesdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesdata',
            name='csv_file_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
