# Generated by Django 3.2.6 on 2021-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slidesdata_csv_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesdata',
            name='image',
            field=models.TextField(),
        ),
    ]
