# Generated by Django 3.2.6 on 2021-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_slidesdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'uploaded_files',
            },
        ),
    ]
