# Generated by Django 3.2.6 on 2021-12-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_uploadedfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidesdata',
            name='csv_file_name',
        ),
        migrations.AddField(
            model_name='slidesdata',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_slidesdata_data_source', to='home.uploadedfiles'),
        ),
    ]
