# Generated by Django 3.2.6 on 2021-12-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211223_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='is_duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
