# Generated by Django 3.2.6 on 2021-12-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_uploadedfiles_is_duplicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidesdata',
            name='quote',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfiles',
            name='background_image',
            field=models.TextField(default=''),
        ),
    ]
