# Generated by Django 3.2.6 on 2021-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211223_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('design', models.JSONField(max_length=250)),
                ('status', models.IntegerField(default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_templates',
            },
        ),
    ]
