# Generated by Django 3.2.6 on 2021-12-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_customtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='template_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtemplate',
            name='template_name',
            field=models.CharField(max_length=250),
        ),
    ]
