# Generated by Django 3.2.6 on 2021-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211228_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
