# Generated by Django 3.2.6 on 2021-12-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customtemplate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesdata',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
