# Generated by Django 3.2.6 on 2021-12-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_customtemplate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mp4Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('is_duplicated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mp4_files',
            },
        ),
    ]
