# Generated by Django 3.2.6 on 2022-01-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_mp4files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesdata',
            name='audio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='honor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='major',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='quote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='school',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
