# Generated by Django 3.2.6 on 2022-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220107_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
