# Generated by Django 3.2.6 on 2022-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_uploadedfiles_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidesdata',
            name='audio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='honor',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='major',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='quote',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='slidesdata',
            name='school',
            field=models.CharField(default='', max_length=250),
        ),
    ]
